params:
  wffile: 'Sn132'
  mprint: 10
  mplot: 0
  mrest: 0
  writeselect: 'r'
  write_isospin: true
  imode: 1
  tfft: True
  nof: 0
  trestart: false

#force:
  #name: 'SLy4'
  #ipair: 0
  #turnoff_zpe: False
  #pair_reg: False
  #delta_fit: [-1.0, -1.0]
  #pair_cutoff: [0.0, 0.0]
  #state_cutoff: [0.0, 0.0]
  #softcut_range: 0.1
  #tbcs: False

grids:
 nx: 48
 ny: 48
 nz: 48
#  dx: 0.8
#  dy: 0.8
#  dz: 0.8
#  bangx: 0.0
#  bangy: 0.0
#  bangz: 0.0
#  tabc_x: 0
#  tabc_y: 0
#  tabc_z: 0
#  periodic: False

levels:
  nneut: 82
  nprot: 50
  # npsi: [82, 50]

static:
  tdiag: false
  tlarge: false
  maxiter: 1200
  radinx: 3.1
  radiny: 3.1
  radinz: 3.1
  serr: 1.0e-20
  x0dmp: 0.45
  e0dmp: 100.0
  tvaryx_0: true
  outerpot: 0
  outertype: 'n'
  ttime: false
  iternat: 0
  iternat_start: 40
  delstepbas: 2.0
  e0bas: 10.0
  pairenhance: 0.0
  iteranneal: 0
  inibcs: 30
  inidiag: 30
  tsort: false
